image: Visual Studio 2017

before_build:
  - dotnet --info
  - dotnet restore

build_script:
  - for /f "delims=" %%i in ('tools\GitVersion.CommandLine\tools\GitVersion.exe /showvariable NuGetVersion') do set NuGetVersion=%%i
  - dotnet build test\InfoCarrier.Core.FunctionalTests\InfoCarrier.Core.FunctionalTests.csproj
  - dotnet pack src\InfoCarrier.Core\InfoCarrier.Core.csproj --output "..\..\artifacts" --configuration Debug --include-symbols

test_script:
  echo DISABLE!!! dotnet test test\InfoCarrier.Core.FunctionalTests\InfoCarrier.Core.FunctionalTests.csproj

artifacts:
  path: artifacts
